### ISSUE TITLE
Installing docker for Mac

### ISSUE THREAD

**Issue by akameron** [davidmerrick/exif-heatmaps#2]
1. Install Homebrew `/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`
1. Tap Cask `brew tap caskroom/cask`
1. Install docker `brew cask install docker`
1. Start docker CMD+SPACE, type docker, enter.

**Comment by davidmerrick** [comment]
Thanks

**Comment by davidmerrick** [comment]
Added this to the README
